# Generated by Django 5.0.6 on 2024-05-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_studentlist_stu_fee_studentlist_stu_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='Stu_Fname',
            field=models.CharField(max_length=100),
        ),
    ]
