# Generated by Django 5.0.6 on 2024-05-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_studentlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carlist',
        ),
    ]
