# Generated by Django 5.0.6 on 2024-05-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_studentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='Stu_Fee',
            field=models.IntegerField(default=50000),
        ),
    ]
