# Generated by Django 5.0.6 on 2024-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_studentlist_stu_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.IntegerField(default=500000),
        ),
    ]
